name: Hello World
on: 
  workflow_dispatch:
    inputs:
      test_suite:
        description: Test suite
        type: choice
        options:
          - functional
          - regression

jobs:
  hello-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Echo text
        run: echo "Hello, world!"
    
    
